#!/usr/bin/env python3
"""kit-manifest.py — checksum manifest of the kit files a consumer receives verbatim (NEB-1835).

A consumer upgraded to 0.38.0 was still running a pre-0.36 `check_code_node.py`: the
installer had refreshed one copy and left another, and nothing compared the installed
bundle with the canonical one at that VERSION. Drift of a single shipped file was silent.
Separately, `source-policy` could not tell a hand-edit from a legitimate installer
refresh, so an agent reverted a correct scaffold update by guesswork.

The manifest closes both: canon records the sha256 of every file it ships verbatim;
the consumer's doctor recomputes them.

  --write [root]    (canon)     regenerate KIT_MANIFEST.sha256 from the source tree
  --check [root]    (canon)     exit 1 if the committed manifest is stale — doctor runs this
  --verify [root]   (consumer)  compare installed files against the shipped manifest:
                                MODIFIED / MISSING under agents/neyra-dev-kit → exit 1
                                (hand-edited or partially upgraded: re-install from canon);
                                MISSING under docs/ → warn (scaffold removed on purpose);
                                UNMANAGED file inside agents/neyra-dev-kit/ → warn
                                (left over from an older install; the retirement pass
                                never deletes what it did not record — remove by hand);
                                manifest version ≠ .neyra-dev-kit.version → exit 1.

The file list is derived from install.sh (NK_TOOL_FILES + the hooks, lib, orchestration
and knowledge copies) so the manifest cannot list something the installer does not ship.
Pure stdlib.
"""
import hashlib
import os
import re
import sys

KIT_REL = "agents/neyra-dev-kit"
MANIFEST_NAME = "KIT_MANIFEST.sha256"
# Shipped by install.sh but never listed: VERSION changes every release and is checked by
# doctor's version stamp; the manifest cannot carry its own hash.
UNLISTED = {"VERSION", MANIFEST_NAME}
# Consumer files that are generated from the canonical source at a different path.
KNOWLEDGE_COPIES = {
    "knowledge/memory_freshness.py": "docs/knowledge/memory_freshness.py",
    "knowledge/check_code_node.py": "docs/knowledge/check_code_node.py",
    "routines/doc-freshness.SKILL.md": "docs/knowledge/routines/doc-freshness.SKILL.md",
}
IGNORED_UNMANAGED = {"__pycache__", ".DS_Store"}


def sha256(path):
    h = hashlib.sha256()
    with open(path, "rb") as fh:
        for chunk in iter(lambda: fh.read(65536), b""):
            h.update(chunk)
    return h.hexdigest()


def tool_files(kit_dir):
    """NK_TOOL_FILES exactly as install.sh declares it — one source of truth."""
    text = open(os.path.join(kit_dir, "install.sh"), encoding="utf-8").read()
    m = re.search(r'^NK_TOOL_FILES="([^"]+)"', text, re.M)
    if not m:
        raise SystemExit("kit-manifest: NK_TOOL_FILES not found in install.sh")
    return m.group(1).split()


def shipped(root):
    """(consumer-relative path, canonical source path) for every verbatim-shipped file."""
    kit_dir = os.path.join(root, KIT_REL)
    out = []

    def add(rel_consumer, src):
        if os.path.isfile(src):
            out.append((rel_consumer, src))

    for name in sorted(os.listdir(os.path.join(kit_dir, "hooks"))):
        if name.endswith(".sh"):
            add(f"{KIT_REL}/hooks/{name}", os.path.join(kit_dir, "hooks", name))
    lib = os.path.join(kit_dir, "hooks", "lib")
    if os.path.isdir(lib):
        for name in sorted(os.listdir(lib)):
            if name.endswith(".sh"):
                add(f"{KIT_REL}/hooks/lib/{name}", os.path.join(lib, name))
    for f in tool_files(kit_dir):
        if f not in UNLISTED:
            add(f"{KIT_REL}/{f}", os.path.join(kit_dir, f))
    orch = os.path.join(kit_dir, "orchestration")
    if os.path.isdir(orch):
        for name in sorted(os.listdir(orch)):
            add(f"{KIT_REL}/orchestration/{name}", os.path.join(orch, name))
    for src_rel, dst_rel in sorted(KNOWLEDGE_COPIES.items()):
        add(dst_rel, os.path.join(kit_dir, src_rel))
    return out


def version(root):
    return open(os.path.join(root, KIT_REL, "VERSION"), encoding="utf-8").read().strip()


def render(root):
    lines = [
        f"# neyra-dev-kit {version(root)} — sha256 of every file install.sh ships verbatim.",
        f"# Generated by kit-manifest.py --write; doctor fails on a stale copy. Do not hand-edit.",
    ]
    for rel, src in shipped(root):
        lines.append(f"{sha256(src)}  {rel}")
    return "\n".join(lines) + "\n"


def parse(text):
    ver, entries = None, {}
    for line in text.splitlines():
        if line.startswith("# neyra-dev-kit "):
            ver = line.split()[2]
        elif line and not line.startswith("#"):
            digest, rel = line.split(None, 1)
            entries[rel.strip()] = digest
    return ver, entries


def cmd_write(root):
    path = os.path.join(root, KIT_REL, MANIFEST_NAME)
    text = render(root)
    with open(path, "w", encoding="utf-8") as fh:
        fh.write(text)
    print(f"kit-manifest: wrote {len(parse(text)[1])} entries → {os.path.relpath(path, root)}")
    return 0


def cmd_check(root):
    path = os.path.join(root, KIT_REL, MANIFEST_NAME)
    if not os.path.isfile(path):
        print(f"FAIL: {KIT_REL}/{MANIFEST_NAME} missing — run kit-manifest.py --write")
        return 1
    have_ver, have = parse(open(path, encoding="utf-8").read())
    want_ver, want = parse(render(root))
    problems = []
    if have_ver != want_ver:
        problems.append(f"header says {have_ver}, VERSION is {want_ver}")
    for rel in sorted(set(have) | set(want)):
        if rel not in want:
            problems.append(f"listed but not shipped: {rel}")
        elif rel not in have:
            problems.append(f"shipped but not listed: {rel}")
        elif have[rel] != want[rel]:
            problems.append(f"changed since --write: {rel}")
    if problems:
        print(f"FAIL: {KIT_REL}/{MANIFEST_NAME} is stale — run `python3 {KIT_REL}/kit-manifest.py --write`:")
        for p in problems:
            print(f"   ✗ {p}")
        return 1
    print(f"ok: kit manifest fresh ({len(want)} shipped files, v{want_ver})")
    return 0


def cmd_verify(root):
    path = os.path.join(root, KIT_REL, MANIFEST_NAME)
    if not os.path.isfile(path):
        print(f"WARN: no {KIT_REL}/{MANIFEST_NAME} — installed from a kit older than 0.48.0; re-install to get bundle integrity")
        return 0
    man_ver, entries = parse(open(path, encoding="utf-8").read())
    fail, warn = [], []
    stamp = os.path.join(root, ".neyra-dev-kit.version")
    inst_ver = open(stamp, encoding="utf-8").read().strip() if os.path.isfile(stamp) else None
    if inst_ver and man_ver != inst_ver:
        fail.append(f"manifest is v{man_ver} but .neyra-dev-kit.version says {inst_ver} — partial upgrade; re-install")
    for rel, digest in sorted(entries.items()):
        p = os.path.join(root, rel)
        if not os.path.isfile(p):
            (fail if rel.startswith(KIT_REL + "/") else warn).append(f"MISSING  {rel}")
        elif sha256(p) != digest:
            fail.append(f"MODIFIED {rel}")
    kit_dir = os.path.join(root, KIT_REL)
    for dirpath, dirnames, filenames in os.walk(kit_dir):
        dirnames[:] = [d for d in dirnames if d not in IGNORED_UNMANAGED]
        for name in filenames:
            rel = os.path.relpath(os.path.join(dirpath, name), root)
            if name in IGNORED_UNMANAGED or rel in entries or name in UNLISTED and dirpath == kit_dir:
                continue
            warn.append(f"UNMANAGED {rel}")
    for w in warn:
        hint = "scaffold absent — re-install restores it" if w.startswith("MISSING") else "not shipped by this kit — left over from an older install; remove by hand"
        print(f"WARN: {w} ({hint})")
    if fail:
        print(f"FAIL: installed kit bundle differs from canonical v{man_ver} — re-install from Neyra-Kit; an intentional change belongs in canon, never in a consumer copy:")
        for f in fail:
            print(f"   ✗ {f}")
        return 1
    print(f"ok: kit bundle matches canonical v{man_ver} ({len(entries)} files)")
    return 0


def main(argv):
    if len(argv) < 2 or argv[1] not in ("--write", "--check", "--verify"):
        print(__doc__.strip())
        return 2
    root = os.path.abspath(argv[2]) if len(argv) > 2 else os.getcwd()
    return {"--write": cmd_write, "--check": cmd_check, "--verify": cmd_verify}[argv[1]](root)


if __name__ == "__main__":
    sys.exit(main(sys.argv))
